# Generated by Django 5.2.4 on 2025-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=255)),
                ('project_size', models.CharField(blank=True, max_length=50)),
                ('timeline', models.CharField(blank=True, max_length=50)),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
